Fix dimensionality error message
Fixes great DimensionalityError that occurs when you pow with a single
value quantity.
DimensionalityError: Cannot convert from 'dimensionless' to
'dimensionless'

Add docs

Add documentation

Add DF accessors, remove docs

Removing docs as I haven't worked out how to set them up properly to
past tests.
DF accessors added to ease going between QAs and numerical arrays.

More accessors

More accessors

Initial hacks to look at adding pandas interface

Getting somewhere, no more errors...

Pass 2 more tests

Get all the pandas tests I can going

Before trying to remove data thing

Something seems to be working e.g.

>>> from pint.pandas_interface import PintArray
>>> import pandas as pd

>>> df = pd.DataFrame({"address": PintArray([1, 2, 3])})
>>> df
          address
0 1 dimensionless
1 2 dimensionless
2 3 dimensionless

>>> df.dtypes
address    Pint
dtype: object

>>> df['address']
0   1 dimensionless
1   2 dimensionless
2   3 dimensionless
Name: address, dtype: Pint

>>> df['address'].values.data
<Quantity([1 2 3], 'dimensionless')>

but unfortunately

>>> df['address'].values
<pint.pandas_interface.PintArray object at 0x117517f28>

Write down my env setup

A minor improvement

Start again, basically

Clean up, ready to start building